apiVersion: batch/v1
kind: Job
metadata:
  name: downloader
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: piyt-downloader
          image: wernight/youtube-dl
          command: ["youtube-dl", "https://www.youtube.com/watch?v=Y2w-wqVod8c"]
      restartPolicy: Never
