apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
spec:
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
        - name: odoo
          image: docker.io/bitnami/odoo:16
          ports:
            - containerPort: 8069
          env:
            - name: ODOO_DATABASE_NAME
              value: "k8smaestro"
            - name: ODOO_DATABASE_USER
              value: "odoo"
            - name: ODOO_DATABASE_PASSWORD
              value: "k8smaestro"
            - name: ODOO_DATABASE_PORT_NUMBER
              value: "5432"
            - name: ODOO_DATABASE_HOST
              value: "postgresql.odoo.svc.cluster.local"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

---
apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: odoo
spec:
  ports:
    - port: 80
      targetPort: 8069
  type: ClusterIP
  selector:
    app: odoo
