apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-app
  template:
    metadata:
      labels:
        app: payment-app
    spec:
      containers:
        - name: busybox-payment
          image: busybox:1.36.0
          command:
            - sh
            - -c
            - |
              echo "MERCHANT_ID: $MERCHANT_ID"
              echo "PAYMENT_GATEWAY_API_KEY: $PAYMENT_GATEWAY_API_KEY"
          env:
            - name: MERCHANT_ID
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: MERCHANT_ID
            - name: PAYMENT_GATEWAY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: PAYMENT_GATEWAY_API_KEY
