apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: httpd-app-rs
  template:
    metadata:
      name: httpd-pod-rs
      labels:
        app: httpd-app-rs
    spec:
      containers:
        - name: httpd-container
          image: httpd
          ports:
            - containerPort: 80